ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.SerializationKt.configureSerialization
      - com.example.SecurityKt.configureSecurity
      - com.example.ThymeleafKt.configureThymeleaf
      - com.example.StatusPagesKt.configureStatusPages
      - com.example.RateLimitingKt.configureRateLimiting
      - com.example.ExposedKt.configureExposed
      - com.example.RoutingKt.configureRouting
